/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef potd_CONSTANTS_H
#define potd_CONSTANTS_H

#include "potd_types.h"



class potdConstants {
 public:
  potdConstants();

};

extern const potdConstants g_potd_constants;



#endif
