/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PotdService_H
#define PotdService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "potd_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PotdServiceIf {
 public:
  virtual ~PotdServiceIf() {}
  virtual void getRandomPoem(Poem& _return) = 0;
};

class PotdServiceIfFactory {
 public:
  typedef PotdServiceIf Handler;

  virtual ~PotdServiceIfFactory() {}

  virtual PotdServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PotdServiceIf* /* handler */) = 0;
};

class PotdServiceIfSingletonFactory : virtual public PotdServiceIfFactory {
 public:
  PotdServiceIfSingletonFactory(const ::std::shared_ptr<PotdServiceIf>& iface) : iface_(iface) {}
  virtual ~PotdServiceIfSingletonFactory() {}

  virtual PotdServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PotdServiceIf* /* handler */) {}

 protected:
  ::std::shared_ptr<PotdServiceIf> iface_;
};

class PotdServiceNull : virtual public PotdServiceIf {
 public:
  virtual ~PotdServiceNull() {}
  void getRandomPoem(Poem& /* _return */) {
    return;
  }
};


class PotdService_getRandomPoem_args {
 public:

  PotdService_getRandomPoem_args(const PotdService_getRandomPoem_args&);
  PotdService_getRandomPoem_args& operator=(const PotdService_getRandomPoem_args&);
  PotdService_getRandomPoem_args() {
  }

  virtual ~PotdService_getRandomPoem_args() noexcept;

  bool operator == (const PotdService_getRandomPoem_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const PotdService_getRandomPoem_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PotdService_getRandomPoem_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PotdService_getRandomPoem_pargs {
 public:


  virtual ~PotdService_getRandomPoem_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PotdService_getRandomPoem_result__isset {
  _PotdService_getRandomPoem_result__isset() : success(false) {}
  bool success :1;
} _PotdService_getRandomPoem_result__isset;

class PotdService_getRandomPoem_result {
 public:

  PotdService_getRandomPoem_result(const PotdService_getRandomPoem_result&);
  PotdService_getRandomPoem_result& operator=(const PotdService_getRandomPoem_result&);
  PotdService_getRandomPoem_result() {
  }

  virtual ~PotdService_getRandomPoem_result() noexcept;
  Poem success;

  _PotdService_getRandomPoem_result__isset __isset;

  void __set_success(const Poem& val);

  bool operator == (const PotdService_getRandomPoem_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PotdService_getRandomPoem_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PotdService_getRandomPoem_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PotdService_getRandomPoem_presult__isset {
  _PotdService_getRandomPoem_presult__isset() : success(false) {}
  bool success :1;
} _PotdService_getRandomPoem_presult__isset;

class PotdService_getRandomPoem_presult {
 public:


  virtual ~PotdService_getRandomPoem_presult() noexcept;
  Poem* success;

  _PotdService_getRandomPoem_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PotdServiceClient : virtual public PotdServiceIf {
 public:
  PotdServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PotdServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getRandomPoem(Poem& _return);
  void send_getRandomPoem();
  void recv_getRandomPoem(Poem& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PotdServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<PotdServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PotdServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getRandomPoem(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PotdServiceProcessor(::std::shared_ptr<PotdServiceIf> iface) :
    iface_(iface) {
    processMap_["getRandomPoem"] = &PotdServiceProcessor::process_getRandomPoem;
  }

  virtual ~PotdServiceProcessor() {}
};

class PotdServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PotdServiceProcessorFactory(const ::std::shared_ptr< PotdServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< PotdServiceIfFactory > handlerFactory_;
};

class PotdServiceMultiface : virtual public PotdServiceIf {
 public:
  PotdServiceMultiface(std::vector<std::shared_ptr<PotdServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PotdServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<PotdServiceIf> > ifaces_;
  PotdServiceMultiface() {}
  void add(::std::shared_ptr<PotdServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getRandomPoem(Poem& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getRandomPoem(_return);
    }
    ifaces_[i]->getRandomPoem(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PotdServiceConcurrentClient : virtual public PotdServiceIf {
 public:
  PotdServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  PotdServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getRandomPoem(Poem& _return);
  int32_t send_getRandomPoem();
  void recv_getRandomPoem(Poem& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
